"""V2 Capability Seed Data — read-only capability registry entries.

These entries are inserted during migration and never modified at runtime.
"""

from __future__ import annotations

from app.v2.capability.contract import CapabilityMaturity

# V2 capability seed data
V2_CAPABILITY_SEED: list[dict[str, str]] = [
    # BE-0 governance artifacts
    {
        "capability_id": "v2.governance.framework",
        "domain": "core",
        "band": "BE-0",
        "maturity": CapabilityMaturity.APPROVED,
        "artifact_status": "complete",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.governance.provenance",
        "domain": "core",
        "band": "BE-0",
        "maturity": CapabilityMaturity.APPROVED,
        "artifact_status": "complete",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.governance.amendment_register",
        "domain": "core",
        "band": "BE-0",
        "maturity": CapabilityMaturity.APPROVED,
        "artifact_status": "complete",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.governance.architecture_principles",
        "domain": "core",
        "band": "BE-0",
        "maturity": CapabilityMaturity.APPROVED,
        "artifact_status": "complete",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.governance.charter",
        "domain": "core",
        "band": "BE-0",
        "maturity": CapabilityMaturity.APPROVED,
        "artifact_status": "complete",
        "version": "1.0.0",
    },
    # BE-1 runtime primitives
    {
        "capability_id": "v2.identifiers",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.audit",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.lineage",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.mode",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.capability_registry",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.errors",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.temporal",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    {
        "capability_id": "v2.rbac",
        "domain": "core",
        "band": "BE-1",
        "maturity": CapabilityMaturity.IMPLEMENTED,
        "artifact_status": "code",
        "version": "1.0.0",
    },
    # Future bands (DESIGNED only)
    {
        "capability_id": "v2.market_data",
        "domain": "market_data",
        "band": "BE-2",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.provider_adapters",
        "domain": "market_data",
        "band": "BE-3",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.market_context",
        "domain": "intelligence",
        "band": "BE-4",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.ml_research",
        "domain": "ml",
        "band": "BE-5",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.portfolio_risk",
        "domain": "portfolio",
        "band": "BE-6",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.simulation",
        "domain": "simulation",
        "band": "BE-7",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.paper_trading",
        "domain": "paper",
        "band": "BE-8",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.broker_connectivity",
        "domain": "broker",
        "band": "BE-9",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.live_execution",
        "domain": "execution",
        "band": "BE-10",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
    {
        "capability_id": "v2.ai_providers",
        "domain": "ai",
        "band": "BE-11",
        "maturity": CapabilityMaturity.DESIGNED,
        "artifact_status": "planned",
        "version": "0.0.0",
    },
]
