import type { QuickActionDefinition } from "./commandTypes";

const catalogueItem = (item: Omit<QuickActionDefinition, "source" | "noActuation">): QuickActionDefinition => ({
  ...item,
  source: "quick-action-catalogue",
  noActuation: true,
});

export const QUICK_ACTION_CATALOGUE: readonly QuickActionDefinition[] = [
  catalogueItem({
    id: "qa.open.operations",
    label: "Open Operations",
    commandType: "navigation",
    group: "Observe",
    target: { kind: "route", route: "/", workspaceId: "monitor.operations" },
    keywords: ["operations", "health", "observe"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.live-market",
    label: "Open Live Market",
    commandType: "navigation",
    group: "Observe",
    target: { kind: "route", route: "/live", workspaceId: "monitor.live_market" },
    keywords: ["market", "observe"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.charts",
    label: "Open Chart Stage",
    commandType: "navigation",
    group: "Observe",
    target: { kind: "route", route: "/?view=chart", workspaceId: "monitor.chart_workspace" },
    keywords: ["charts", "chart", "stage", "observe", "annotations"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.signals",
    label: "Open Signals Dock",
    commandType: "navigation",
    group: "Detect",
    target: { kind: "route", route: "/?dock=signals", workspaceId: "research.advisory_signals" },
    keywords: ["signals", "detect", "dock", "stream"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.analytics",
    label: "Open Intelligence Dock",
    commandType: "navigation",
    group: "Analyze",
    target: { kind: "route", route: "/?dock=intelligence", workspaceId: "research.analytics" },
    keywords: ["analytics", "intelligence", "analyze", "dock"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.intelligence",
    label: "Open Institutional Intelligence",
    commandType: "navigation",
    group: "Analyze",
    target: { kind: "route", route: "/intelligence", workspaceId: "research.intelligence" },
    keywords: ["intelligence", "reports", "analyze"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.investigation",
    label: "Open Signal Investigation",
    commandType: "navigation",
    group: "Investigate",
    target: { kind: "route", route: "/investigate", workspaceId: "investigate.signal_investigation" },
    keywords: ["investigation", "signal"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.scenario-comparison",
    label: "Open Scenario Comparison",
    commandType: "navigation",
    group: "Compare",
    target: { kind: "route", route: "/compare-scenarios", workspaceId: "compare.scenarios" },
    keywords: ["scenario", "compare"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.trade-planning",
    label: "Open Trade Planning",
    commandType: "navigation",
    group: "Plan",
    target: { kind: "route", route: "/trade-plans", workspaceId: "plan.trade_plans" },
    keywords: ["planning", "research notes"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.execution-research",
    label: "Open Execution Research",
    commandType: "navigation",
    group: "Plan",
    // SURF-P01: the palette command targets the post-absorption destination
    // directly (/?view=execution) rather than the legacy redirect.
    target: { kind: "route", route: "/?view=execution", workspaceId: "plan.execution_research" },
    keywords: ["simulated", "research"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.portfolio-research",
    label: "Open Portfolio Research",
    commandType: "navigation",
    group: "Review",
    target: { kind: "route", route: "/portfolio-research", workspaceId: "review.portfolio_research" },
    keywords: ["portfolio", "review"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.journal",
    label: "Open Research Journal",
    commandType: "navigation",
    group: "Document",
    target: { kind: "route", route: "/journal", workspaceId: "review.journal" },
    keywords: ["journal", "document"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.research-management",
    label: "Open Research Management",
    commandType: "navigation",
    group: "Document",
    // UI-CONV-P03 item 4: the palette command targets the post-absorption
    // destination directly (/?view=research) rather than the legacy redirect.
    target: { kind: "route", route: "/?view=research", workspaceId: "review.research_management" },
    keywords: ["collections", "tags", "document"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.governance-evidence",
    label: "Open Governance & Evidence",
    commandType: "navigation",
    group: "Govern",
    target: { kind: "route", route: "/governance", workspaceId: "govern.governance_evidence" },
    keywords: ["governance", "evidence", "audit", "readiness"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.workspace-settings",
    label: "Open Workspace Settings",
    commandType: "navigation",
    group: "Settings",
    target: { kind: "route", route: "/workspace", workspaceId: "settings.workspace" },
    keywords: ["settings", "preferences"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.previous-workspace",
    label: "Return to Previous Workspace",
    commandType: "navigation",
    group: "Shell Controls",
    target: { kind: "previous-workspace" },
    keywords: ["previous", "back", "workspace"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.recent-workspace",
    label: "Open Recent Workspace",
    commandType: "navigation",
    group: "Shell Controls",
    target: { kind: "recent-workspace" },
    keywords: ["recent", "workspace"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.toggle.navigation-dock",
    label: "Toggle Navigation Dock",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "toggle-navigation" },
    keywords: ["navigation", "dock"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.toggle.context-panel",
    label: "Toggle Context Panel",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "toggle-context" },
    keywords: ["context", "panel"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.toggle.activity-dock",
    label: "Toggle Activity Dock",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "toggle-activity" },
    keywords: ["activity", "dock"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.toggle.theme",
    label: "Toggle Institutional Theme",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "toggle-theme" },
    keywords: ["theme", "light", "dark"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.global-search",
    label: "Open Global Search",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "open-global-search" },
    keywords: ["search", "find"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.clear.search-query",
    label: "Clear Search Query",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "clear-search-query" },
    keywords: ["search", "clear"],
    enabled: false,
  }),
  catalogueItem({
    id: "qa.open.shell-status",
    label: "Open Shell Status Dialog",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "open-shell-status" },
    keywords: ["status", "shell"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.show.governance-notification",
    label: "Show Governance Status",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "show-governance-notification" },
    keywords: ["governance", "status"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.focus.navigation",
    label: "Focus Navigation Dock",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "focus-navigation" },
    keywords: ["focus", "navigation"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.focus.workspace",
    label: "Focus Primary Workspace",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "focus-workspace" },
    keywords: ["focus", "workspace"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.focus.context",
    label: "Focus Context Panel",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "focus-context" },
    keywords: ["focus", "context"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.focus.activity",
    label: "Focus Activity Dock",
    commandType: "ui-toggle",
    group: "Shell Controls",
    target: { kind: "shell", action: "focus-activity" },
    keywords: ["focus", "activity"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.assistant-surfaces",
    label: "Open Assistant Surfaces",
    commandType: "navigation",
    group: "Assistant",
    target: { kind: "route", route: "/intelligence", workspaceId: "research.intelligence" },
    keywords: ["assistant", "audit", "navigate"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.recent-assistant-responses",
    label: "Open Recent Assistant Responses",
    commandType: "navigation",
    group: "Assistant",
    target: { kind: "route", route: "/intelligence", workspaceId: "research.intelligence" },
    keywords: ["assistant", "responses", "history"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.assistant-refusals-audit",
    label: "Open Assistant Refusals Audit",
    commandType: "navigation",
    group: "Assistant",
    target: { kind: "route", route: "/governance", workspaceId: "govern.governance_evidence" },
    keywords: ["assistant", "refusals", "audit", "review"],
    enabled: true,
  }),
  catalogueItem({
    id: "qa.open.documentation-lookup",
    label: "Open Documentation Lookup",
    commandType: "navigation",
    group: "Assistant",
    target: { kind: "route", route: "/intelligence", workspaceId: "research.intelligence" },
    keywords: ["documentation", "lookup", "reference"],
    enabled: true,
  }),
] as const;

export const QUICK_ACTION_CATALOGUE_IDS = QUICK_ACTION_CATALOGUE.map((item) => item.id);
