"""Institutional Platform security/API foundation (Wave 7)."""

from app.institutional_platform.api_catalogue import (
    API_ROUTE_VERSION,
    CATALOGUE_VERSION,
    CATALOGUED_TAGS,
    ApiCatalogueRoute,
    build_api_catalogue,
)
from app.institutional_platform.plugins import (
    PLUGIN_CAPABILITY_ALLOWLIST,
    PLUGIN_CONTRACT_VERSION,
    PUBLISHED_PLUGIN_CONTRACTS,
    PluginContractDecision,
    PluginContractRequest,
    PluginContractSafetyService,
    PublishedPluginContract,
)
from app.institutional_platform.portfolio_research import (
    PORTFOLIO_RESEARCH_DISCLAIMER,
    PORTFOLIO_RESEARCH_STATUS,
    PORTFOLIO_RESEARCH_VERSION,
    PortfolioResearchMetric,
    PortfolioResearchService,
    PortfolioResearchSnapshot,
)
from app.institutional_platform.preferences import (
    ALLOWED_VISIBLE_MODULES,
    PREFERENCE_RESEARCH_STATUS,
    WORKSPACE_PREFERENCE_FORBIDDEN_FIELDS,
    WORKSPACE_PREFERENCE_SECRET_MARKERS,
    WorkspacePreferenceDraft,
    WorkspacePreferenceFactory,
    WorkspacePreferenceRepository,
)
from app.institutional_platform.rbac import (
    FORBIDDEN_PERMISSION_MARKERS,
    INSTITUTIONAL_ROLE_PERMISSIONS,
    INSTITUTIONAL_ROUTE_INVENTORY,
    InstitutionalPermission,
    InstitutionalScopeRecord,
    assert_permission_vocabulary_safe,
    permissions_for_role,
    require_institutional_permission,
)
from app.institutional_platform.readiness import (
    ADMIN_DEFAULT_CREDENTIAL_DISPOSITION,
    RATE_GUARD_DISPOSITION,
    RATE_GUARD_TECHNICAL_DEBT_ID,
    READINESS_VERSION,
    ReadinessDisposition,
    readiness_dispositions,
)
from app.institutional_platform.research_management import (
    ARTIFACT_ID_COLUMNS,
    RESEARCH_MANAGEMENT_FORBIDDEN_FIELDS,
    RESEARCH_MANAGEMENT_SECRET_OR_PII_MARKERS,
    RESEARCH_MANAGEMENT_STATUS,
    ResearchArtifactReference,
    ResearchCollectionDraft,
    ResearchManagementFactory,
    ResearchManagementRepository,
    ResearchTagDraft,
)

__all__ = [
    "ALLOWED_VISIBLE_MODULES",
    "API_ROUTE_VERSION",
    "ApiCatalogueRoute",
    "CATALOGUE_VERSION",
    "CATALOGUED_TAGS",
    "FORBIDDEN_PERMISSION_MARKERS",
    "INSTITUTIONAL_ROUTE_INVENTORY",
    "INSTITUTIONAL_ROLE_PERMISSIONS",
    "InstitutionalPermission",
    "InstitutionalScopeRecord",
    "ARTIFACT_ID_COLUMNS",
    "PREFERENCE_RESEARCH_STATUS",
    "PORTFOLIO_RESEARCH_DISCLAIMER",
    "PORTFOLIO_RESEARCH_STATUS",
    "PORTFOLIO_RESEARCH_VERSION",
    "PLUGIN_CAPABILITY_ALLOWLIST",
    "PLUGIN_CONTRACT_VERSION",
    "PUBLISHED_PLUGIN_CONTRACTS",
    "RATE_GUARD_DISPOSITION",
    "RATE_GUARD_TECHNICAL_DEBT_ID",
    "READINESS_VERSION",
    "RESEARCH_MANAGEMENT_FORBIDDEN_FIELDS",
    "RESEARCH_MANAGEMENT_SECRET_OR_PII_MARKERS",
    "RESEARCH_MANAGEMENT_STATUS",
    "WORKSPACE_PREFERENCE_FORBIDDEN_FIELDS",
    "WORKSPACE_PREFERENCE_SECRET_MARKERS",
    "ADMIN_DEFAULT_CREDENTIAL_DISPOSITION",
    "PluginContractDecision",
    "PluginContractRequest",
    "PluginContractSafetyService",
    "PortfolioResearchMetric",
    "PortfolioResearchService",
    "PortfolioResearchSnapshot",
    "PublishedPluginContract",
    "ReadinessDisposition",
    "ResearchArtifactReference",
    "ResearchCollectionDraft",
    "ResearchManagementFactory",
    "ResearchManagementRepository",
    "ResearchTagDraft",
    "WorkspacePreferenceDraft",
    "WorkspacePreferenceFactory",
    "WorkspacePreferenceRepository",
    "assert_permission_vocabulary_safe",
    "build_api_catalogue",
    "permissions_for_role",
    "readiness_dispositions",
    "require_institutional_permission",
]
