import type { WorkflowNavigationMetadata } from "./workflowTypes";

export const WORKFLOW_NAVIGATION_METADATA: readonly WorkflowNavigationMetadata[] = [
  {
    workspaceId: "monitor.operations",
    primaryStage: "Observe",
    secondaryStages: ["Govern"],
    breadcrumbLabel: "Operations",
    workflowOrdinal: 10,
    keywords: ["operations", "health", "alerts", "governance"],
    relatedWorkspaceIds: ["monitor.live_market", "monitor.chart_workspace", "research.advisory_signals"],
    defaultNextWorkspaceIds: ["monitor.live_market", "research.advisory_signals"],
    defaultPreviousWorkspaceIds: [],
  },
  {
    workspaceId: "monitor.live_market",
    primaryStage: "Observe",
    breadcrumbLabel: "Live Market",
    workflowOrdinal: 20,
    keywords: ["market", "status", "observation"],
    relatedWorkspaceIds: ["monitor.chart_workspace", "research.advisory_signals"],
    defaultNextWorkspaceIds: ["monitor.chart_workspace", "research.advisory_signals"],
    defaultPreviousWorkspaceIds: ["monitor.operations"],
  },
  {
    workspaceId: "monitor.chart_workspace",
    primaryStage: "Observe",
    secondaryStages: ["Investigate"],
    breadcrumbLabel: "Chart Workspace",
    workflowOrdinal: 30,
    keywords: ["charts", "annotations", "market", "research"],
    relatedWorkspaceIds: ["research.advisory_signals", "investigate.signal_investigation", "review.journal"],
    defaultNextWorkspaceIds: ["research.advisory_signals", "investigate.signal_investigation"],
    defaultPreviousWorkspaceIds: ["monitor.live_market"],
  },
  {
    workspaceId: "monitor.chart_alias",
    primaryStage: "Observe",
    secondaryStages: ["Investigate"],
    breadcrumbLabel: "Chart Workspace",
    workflowOrdinal: 31,
    keywords: ["chart", "compatibility", "alias"],
    relatedWorkspaceIds: ["monitor.chart_workspace"],
    defaultNextWorkspaceIds: ["research.advisory_signals"],
    defaultPreviousWorkspaceIds: ["monitor.live_market"],
  },
  {
    workspaceId: "research.advisory_signals",
    primaryStage: "Detect",
    breadcrumbLabel: "Advisory Signals",
    workflowOrdinal: 40,
    keywords: ["signals", "detect", "guardrails", "rationale"],
    relatedWorkspaceIds: ["investigate.signal_investigation", "research.analytics", "research.intelligence"],
    defaultNextWorkspaceIds: ["investigate.signal_investigation", "research.analytics"],
    defaultPreviousWorkspaceIds: ["monitor.chart_workspace"],
  },
  {
    workspaceId: "research.analytics",
    primaryStage: "Analyze",
    secondaryStages: ["Review"],
    breadcrumbLabel: "Performance Analytics",
    workflowOrdinal: 50,
    keywords: ["analytics", "calibration", "performance", "uncertainty"],
    relatedWorkspaceIds: ["research.intelligence", "review.portfolio_research"],
    defaultNextWorkspaceIds: ["research.intelligence", "review.portfolio_research"],
    defaultPreviousWorkspaceIds: ["research.advisory_signals"],
  },
  {
    workspaceId: "research.intelligence",
    primaryStage: "Analyze",
    breadcrumbLabel: "Institutional Intelligence",
    workflowOrdinal: 60,
    keywords: ["intelligence", "reports", "evidence", "uncertainty"],
    relatedWorkspaceIds: ["compare.scenarios", "investigate.signal_investigation", "review.research_management"],
    defaultNextWorkspaceIds: ["compare.scenarios", "review.research_management"],
    defaultPreviousWorkspaceIds: ["research.analytics", "investigate.signal_investigation"],
  },
  {
    workspaceId: "investigate.signal_investigation",
    primaryStage: "Investigate",
    breadcrumbLabel: "Signal Investigation",
    workflowOrdinal: 70,
    keywords: ["investigation", "lineage", "guardrails", "signal"],
    relatedWorkspaceIds: ["research.intelligence", "compare.scenarios", "plan.trade_plans"],
    defaultNextWorkspaceIds: ["research.intelligence", "compare.scenarios"],
    defaultPreviousWorkspaceIds: ["research.advisory_signals", "monitor.chart_workspace"],
  },
  {
    workspaceId: "compare.scenarios",
    primaryStage: "Compare",
    breadcrumbLabel: "Scenario Comparison",
    workflowOrdinal: 80,
    keywords: ["scenarios", "comparison", "hypothetical"],
    relatedWorkspaceIds: ["plan.trade_plans", "review.journal", "review.portfolio_research"],
    defaultNextWorkspaceIds: ["plan.trade_plans", "review.journal"],
    defaultPreviousWorkspaceIds: ["research.intelligence", "investigate.signal_investigation"],
  },
  {
    workspaceId: "plan.trade_plans",
    primaryStage: "Plan",
    breadcrumbLabel: "Trade Planning",
    workflowOrdinal: 90,
    keywords: ["planning", "hypothesis", "notes", "research"],
    relatedWorkspaceIds: ["plan.execution_research", "review.journal"],
    defaultNextWorkspaceIds: ["plan.execution_research", "review.journal"],
    defaultPreviousWorkspaceIds: ["compare.scenarios", "investigate.signal_investigation"],
  },
  {
    workspaceId: "plan.execution_research",
    primaryStage: "Plan",
    secondaryStages: ["Review"],
    breadcrumbLabel: "Execution Research",
    workflowOrdinal: 100,
    keywords: ["simulated", "research", "replay", "analytics"],
    relatedWorkspaceIds: ["review.portfolio_research", "review.journal"],
    defaultNextWorkspaceIds: ["review.portfolio_research", "review.journal"],
    defaultPreviousWorkspaceIds: ["plan.trade_plans"],
  },
  {
    workspaceId: "review.portfolio_research",
    primaryStage: "Review",
    breadcrumbLabel: "Portfolio Research",
    workflowOrdinal: 110,
    keywords: ["portfolio", "review", "aggregate", "reports"],
    relatedWorkspaceIds: ["review.research_management", "monitor.operations"],
    defaultNextWorkspaceIds: ["review.research_management", "monitor.operations"],
    defaultPreviousWorkspaceIds: ["plan.execution_research", "compare.scenarios"],
  },
  {
    workspaceId: "review.journal",
    primaryStage: "Document",
    breadcrumbLabel: "Research Journal",
    workflowOrdinal: 120,
    keywords: ["journal", "document", "lessons", "reflections"],
    relatedWorkspaceIds: ["review.research_management", "review.portfolio_research"],
    defaultNextWorkspaceIds: ["review.research_management", "review.portfolio_research"],
    defaultPreviousWorkspaceIds: ["plan.trade_plans", "compare.scenarios"],
  },
  {
    workspaceId: "review.research_management",
    primaryStage: "Document",
    secondaryStages: ["Review"],
    breadcrumbLabel: "Research Management",
    workflowOrdinal: 130,
    keywords: ["collections", "tags", "artifacts", "organization"],
    relatedWorkspaceIds: ["review.portfolio_research", "monitor.operations"],
    defaultNextWorkspaceIds: ["review.portfolio_research", "monitor.operations"],
    defaultPreviousWorkspaceIds: ["review.journal", "research.intelligence"],
  },
  {
    workspaceId: "govern.governance_evidence",
    primaryStage: "Govern",
    breadcrumbLabel: "Governance & Evidence",
    workflowOrdinal: 135,
    keywords: ["governance", "evidence", "audit", "readiness", "version"],
    relatedWorkspaceIds: ["monitor.operations", "review.research_management"],
    defaultNextWorkspaceIds: ["monitor.operations"],
    defaultPreviousWorkspaceIds: ["review.research_management", "monitor.operations"],
  },
  {
    workspaceId: "settings.workspace",
    primaryStage: "Settings",
    breadcrumbLabel: "Workspace Settings",
    workflowOrdinal: 140,
    keywords: ["settings", "preferences", "presentation"],
    relatedWorkspaceIds: ["monitor.operations"],
    defaultNextWorkspaceIds: ["monitor.operations"],
    defaultPreviousWorkspaceIds: ["monitor.operations"],
  },
] as const;
